version: 0.0  
os: linux
files:
  - source: /magento
    destination: /data/websites/elsevierasia/

hooks:
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 1200
      runas: root
  BeforeAllowTraffic:
    - location: deploy-scripts/pre_tasks.sh
      runas: root
  AfterInstall:
    - location: deploy-scripts/after_install.sh
      timeout: 1200
      runas: root
