name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: BUILD
        env:
          AUTH_JSON_GH: ${{ secrets.AUTH_JSON_BB }}
        run: |
          echo $AUTH_JSON_GH > auth.json
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update -y
          sudo apt install php7.2
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.1
          composer install
          bin/magento setup:di:compile
          
