name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [m]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: BUILD
        env:
          AUTH_JSON_GH: ${{ secrets.AUTH_JSON_BB }}
        run: |
          echo $AUTH_JSON_GH > auth.json
          apt-get update && apt-get install -y openssh-client
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.1
          composer install
          bin/magento setup:di:compile
        
      - name: Run code quality elsevier
        run: vendor/bin/phpcs --standard=magento-coding-standard/magento-coding-standard/Magento2 app/code/SmartOsc/
      
